services:
  docker-gen:
    image: nginxproxy/docker-gen:${DOCKERGEN_TAG:-latest}
    command: -notify-sighup app-pixelcloud-nginxproxy-nginx -watch -wait 500ms:3s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: app-pixelcloud-nginxproxy-dgen
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    environment:
      ENABLE_IPV6: ${ENABLE_IPV6:-false}
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  nginx:
    image: pixelfordinner/nginx:${NGINX_TAG:-latest}
    container_name: app-pixelcloud-nginxproxy-nginx
    restart: unless-stopped
    depends_on:
      - docker-gen
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./volumes/nginx/html:/usr/share/nginx/html:ro
    networks:
      - edge-tier
      - default
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  acme-companion:
    image: nginxproxy/acme-companion:${COMPANION_TAG:-latest}
    container_name: app-pixelcloud-nginxproxy-acme
    restart: unless-stopped
    depends_on:
      - docker-gen
      - nginx
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs
      - ./volumes/nginx/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: app-pixelcloud-nginxproxy-dgen
      NGINX_PROXY_CONTAINER: app-pixelcloud-nginxproxy-nginx
      ACME_CA_URI: ${ACME_CA_URI:-}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEBUG: ${DEBUG:-0}
    logging:
      options:
        max-size: '4m'
        max-file: '10'

networks:
  default:
    name: nginx-proxy
    external: true
  edge-tier:
    name: edge
    external: true
