services:
  scheduler:
    restart: unless-stopped
    container_name: app-pixelcloud-scheduler
    image: mcuadros/ofelia:0.3
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.keep-alive.schedule: "@every 24h"
      ofelia.job-local.keep-alive.command: "true"
