services:
  scheduler:
    restart: unless-stopped
    container_name: app-pixelcloud-scheduler
    image: ghcr.io/netresearch/ofelia:v0.6.6
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

