version: '3.7'

services:
  scheduler:
    restart: unless-stopped
    container_name: app-pixelcloud-scheduler
    image: pixelfordinner/ofelia
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.keep-alive.schedule: "@every 24h"
      ofelia.job-local.keep-alive.command: "true"
